### ISSUE TITLE
Documentation link with 404

### ISSUE THREAD

**Issue by HelioGuilherme66** [salabs/robotframework-seleniumtestability#2]
I have just followed the link from the README to the documentation page, and got a 404 error.
![image](https://user-images.githubusercontent.com/2866630/63839836-ee6e2d80-c977-11e9-8a13-08af9574c0e0.png)

http://omenia.github.io/robotframework-seleniumtestability

**Comment by rasjani** [comment]
The whole readme is outdated due to complete rewrite to use incoming SeleniumLibrary changes.  For now,  the usage is described in docs/keywords.html
